#!/usr/bin/env python3
"""
reportGenerator.py — Audit Report Generation Module
Generates formatted security audit reports in TXT and JSON formats.
"""

import json
import os
from datetime import datetime

from rich.console import Console

console = Console()


class ReportGenerator:
    """Generates security audit reports from scan results."""

    def __init__(self, outputDir="reports/"):
        """
        Initialize the report generator.

        Args:
            outputDir: Directory to save reports to.
        """
        self.outputDir = outputDir
        os.makedirs(outputDir, exist_ok=True)

    def generateReport(self, scanResults, duration):
        """
        Generate both TXT and JSON audit reports.

        Args:
            scanResults: List of scan result dicts from the audit.
            duration: Audit duration in seconds.

        Returns:
            Path to the generated TXT report.
        """
        timestamp = datetime.now()
        dateStr = timestamp.strftime("%Y-%m-%d_%H-%M-%S")

        txtPath = self._generateTxtReport(scanResults, duration, timestamp, dateStr)
        jsonPath = self._generateJsonReport(scanResults, duration, timestamp, dateStr)

        console.print(f"[dim]  TXT report: {txtPath}[/dim]")
        console.print(f"[dim]  JSON report: {jsonPath}[/dim]")

        return txtPath

    def _generateTxtReport(self, scanResults, duration, timestamp, dateStr):
        """Generate a human-readable TXT report."""
        reportPath = os.path.join(self.outputDir, f"pureAudit_{dateStr}.txt")

        totalDevices = len(scanResults)
        totalPorts = sum(len(r["ports"]) for r in scanResults)
        totalFlags = sum(len(r["flags"]) for r in scanResults)

        criticalCount = sum(
            1 for r in scanResults
            for f in r["flags"]
            if f["severity"] == "CRITICAL"
        )
        highCount = sum(
            1 for r in scanResults
            for f in r["flags"]
            if f["severity"] == "HIGH"
        )
        mediumCount = sum(
            1 for r in scanResults
            for f in r["flags"]
            if f["severity"] == "MEDIUM"
        )

        lines = []
        lines.append("=" * 60)
        lines.append("  PUREAUDIT — Network Security Audit Report")
        lines.append("  Generated by PureSecure | https://puresecure.cloud")
        lines.append("=" * 60)
        lines.append("")
        lines.append(f"  Date:       {timestamp.strftime('%B %d, %Y at %I:%M %p')}")
        lines.append(f"  Duration:   {duration:.1f} seconds")
        lines.append(f"  Devices:    {totalDevices} discovered")
        lines.append(f"  Open Ports: {totalPorts} detected")
        lines.append(f"  Issues:     {totalFlags} flagged")
        lines.append(f"    CRITICAL: {criticalCount}")
        lines.append(f"    HIGH:     {highCount}")
        lines.append(f"    MEDIUM:   {mediumCount}")
        lines.append("")
        lines.append("-" * 60)

        # Device details
        for idx, result in enumerate(scanResults, 1):
            lines.append("")
            lines.append(f"  DEVICE {idx}: {result['ip']}")
            lines.append(f"    MAC:      {result['mac']}")
            lines.append(f"    Hostname: {result['hostname']}")
            lines.append("")

            # Open ports
            if result["ports"]:
                lines.append("    Open Ports:")
                for port in result["ports"]:
                    lines.append(f"      - {port['port']}/{port['service']} ({port['state']})")
            else:
                lines.append("    Open Ports: None detected")

            lines.append("")

            # Vulnerability flags
            if result["flags"]:
                lines.append("    Security Issues:")
                for flag in result["flags"]:
                    lines.append(f"      [{flag['severity']}] Port {flag['port']}/{flag['service']}")
                    lines.append(f"        Risk: {flag['reason']}")
                    lines.append(f"        Fix:  {flag['recommendation']}")
                    lines.append("")
            else:
                lines.append("    Security Issues: None — looking good!")

            lines.append("-" * 60)

        # Footer
        lines.append("")
        lines.append("  RECOMMENDATIONS:")
        lines.append("  1. Address all CRITICAL issues immediately")
        lines.append("  2. Schedule HIGH issues for remediation this week")
        lines.append("  3. Review MEDIUM issues during next maintenance window")
        lines.append("  4. Consider a PureSecure consultation for hands-on help")
        lines.append("")
        lines.append("  For professional remediation, visit https://puresecure.cloud")
        lines.append("  or contact support@puresecure.cloud")
        lines.append("")
        lines.append("=" * 60)
        lines.append("  Report generated by PureAudit v1.0")
        lines.append("=" * 60)

        with open(reportPath, "w") as f:
            f.write("\n".join(lines))

        return reportPath

    def _generateJsonReport(self, scanResults, duration, timestamp, dateStr):
        """Generate a machine-readable JSON report."""
        reportPath = os.path.join(self.outputDir, f"pureAudit_{dateStr}.json")

        report = {
            "metadata": {
                "tool": "PureAudit v1.0",
                "generatedBy": "PureSecure",
                "website": "https://puresecure.cloud",
                "timestamp": timestamp.isoformat(),
                "durationSeconds": round(duration, 1)
            },
            "summary": {
                "totalDevices": len(scanResults),
                "totalOpenPorts": sum(len(r["ports"]) for r in scanResults),
                "totalIssues": sum(len(r["flags"]) for r in scanResults),
                "bySeverity": {
                    "critical": sum(1 for r in scanResults for f in r["flags"] if f["severity"] == "CRITICAL"),
                    "high": sum(1 for r in scanResults for f in r["flags"] if f["severity"] == "HIGH"),
                    "medium": sum(1 for r in scanResults for f in r["flags"] if f["severity"] == "MEDIUM")
                }
            },
            "devices": scanResults
        }

        with open(reportPath, "w") as f:
            json.dump(report, f, indent=2)

        return reportPath
